### PR TITLE
Accept --json flag converting the output to JSON when using CLI

### PR DESCRIPTION
**Pull request by stoyandimov**
P.S. Feel free to edit or ignore this PR if the lack of tests or the use case concern you in anyway. I run across an issue with parsing the  CLI output as JSON and decide to send a PR with my own solution.

# Current situation
Getting tournament information via the CLI outputs the data as a dictionary. Some of the endpoints return data that is easily parsable as JSON. But once the API returns dates or decimal values, then JSON prrsers are failing.  For example, here `startDate` has an invalid JSON value:

```
numerapi profile integration_test

# outputs:
{   'bio': 'The official example model. Submits example predictions.',
    'id': '59de8728-38e5-45bd-a3d5-9d4ad649dd3f',
    'startDate': datetime.datetime(2018, 6, 6, 17, 33, 21, tzinfo=tzutc()),
    'totalStake': '60.181006030114101196',
    'username': 'integration_test'}
```

# Desired situation
Accept an `--json` argument that converts the dictionary to JSON format:

```
numerapi --json profile integration_test

# outputs:
{
    "bio": "The official example model. Submits example predictions.",
    "id": "59de8728-38e5-45bd-a3d5-9d4ad649dd3f",
    "startDate": "2018-06-06T17:33:21+00:00",
    "totalStake": "60.181006030114101196",
    "username": "integration_test"
}
```

In this case, values like `datetime` and `decimal.Decimal` are converted to something that JSON parsers like `jq` can handle.

### CODE REVIEW

**Review by uuazed — CHANGES_REQUESTED** [review]
Thx! Finally someone that is interested in the cli version :-) 

You are perfectly right, having python objects in the cli output isn't useful at all. So I suggest making your change the default behavior and remove the --json flag.

**Comment by stoyandimov** [comment]
Great idea. I'll do that.

When do you and/or Numerai release? If I have time, I might look into directly outputting the JSON (with a filter) from the API response, instead of desalinizing it to dict. and then serializing the dict. again to JSON.

**Comment by uuazed** [comment]
Cool! I was also thinking of skipping the serialize / deserialize step. It probably requires more code changes, compared to the custom json decoder. Maybe there is some elegant way using a decorator. However, I am also fine with your current implementation

there is no release schedule, I decide ad-hoc if and when a new version gets released.

**Comment by stoyandimov** [comment]
Done, I wonder if it should may be be release as a major update. It's basically a breaking change for the developers that expect python dict output.

**Review by uuazed — APPROVED** [review]

**Pull request merged**
